# docker run -it --rm mysql mysql -h 192.168.1.215 --port 30300 -u root -p

version: '3'
services:

# TODO the following use extra_hosts, but its not necessary for locally deployed services. we should rename
# the services kdc-mf-*, so that it works inside DC as well as outside

  kdc-mf-contracts:
    image: maxant/jdk
    container_name: kdc-mf-contracts
    ports:
      - "8080:8080"
    environment:
      quarkus.datasource.jdbc.url: "jdbc:mysql://zeus.com:30300/mfcontracts"
      kafka.bootstrap.servers: "zeus.com:30001,zeus.com:30002"
      quarkus.log.handler.gelf.host: "zeus.com"
      quarkus.elasticsearch.hosts: "kdc.elasticsearch.zeus.com"
    volumes:
      - ./mf/contracts/target:/project
    command:
      java -jar contracts-1.0-SNAPSHOT-runner.jar -Xmx300m
    extra_hosts:
      - "contracts:127.0.0.1"
      - "pricing:127.0.0.1"
      - "web:127.0.0.1"
      - "partners:127.0.0.1"
      - "cases:127.0.0.1"
      - "waitingroom:127.0.0.1"
      - "organisation:127.0.0.1"
      - "zeus.com:192.168.1.215"
      - "kdc.elasticsearch.zeus.com:192.168.1.215"
      - "kdc.schemaregistry.zeus.com:192.168.1.215"
  kdc-mf-pricing:
    image: maxant/jdk
    container_name: kdc-mf-pricing
    ports:
      - "8081:8081"
    environment:
      quarkus.datasource.jdbc.url: "jdbc:mysql://zeus.com:30300/mfpricing"
      kafka.bootstrap.servers: "zeus.com:30001,zeus.com:30002"
      quarkus.log.handler.gelf.host: "zeus.com"
    volumes:
      - ./mf/pricing/target:/project
    command:
      java -jar pricing-1.0-SNAPSHOT-runner.jar -Xmx300m
    extra_hosts:
      - "contracts:127.0.0.1"
      - "pricing:127.0.0.1"
      - "web:127.0.0.1"
      - "partners:127.0.0.1"
      - "cases:127.0.0.1"
      - "waitingroom:127.0.0.1"
      - "organisation:127.0.0.1"
      - "zeus.com:192.168.1.215"
      - "kdc.elasticsearch.zeus.com:192.168.1.215"
      - "kdc.schemaregistry.zeus.com:192.168.1.215"

  kdc-mf-web:
    image: maxant/jdk
    container_name: kdc-mf-web
    ports:
      - "8082:8082"
    environment:
      kafka.bootstrap.servers: "zeus.com:30001,zeus.com:30002"
      quarkus.log.handler.gelf.host: "zeus.com"
      ch.maxant.kdc.mf.components.elasticsearch.url: "http://kdc.elasticsearch.zeus.com"
    volumes:
      - ./mf/web/target:/project
    command:
      java -jar web-1.0-SNAPSHOT-runner.jar -Xmx300m
    extra_hosts:
      - "contracts:127.0.0.1"
      - "pricing:127.0.0.1"
      - "web:127.0.0.1"
      - "partners:127.0.0.1"
      - "cases:127.0.0.1"
      - "waitingroom:127.0.0.1"
      - "organisation:127.0.0.1"
      - "zeus.com:192.168.1.215"
      - "kdc.elasticsearch.zeus.com:192.168.1.215"
      - "kdc.schemaregistry.zeus.com:192.168.1.215"

  kdc-mf-partners:
    image: maxant/jdk
    container_name: kdc-mf-partners
    ports:
      - "8083:8083"
    environment:
      quarkus.datasource.jdbc.url: "jdbc:mysql://zeus.com:30300/mfpartners"
      kafka.bootstrap.servers: "zeus.com:30001,zeus.com:30002"
      quarkus.log.handler.gelf.host: "zeus.com"
      quarkus.elasticsearch.hosts: "kdc.elasticsearch.zeus.com"
    volumes:
      - ./mf/partners/target:/project
    command:
      java -jar partners-1.0-SNAPSHOT-runner.jar -Xmx300m
    extra_hosts:
      - "contracts:127.0.0.1"
      - "pricing:127.0.0.1"
      - "web:127.0.0.1"
      - "partners:127.0.0.1"
      - "cases:127.0.0.1"
      - "waitingroom:127.0.0.1"
      - "organisation:127.0.0.1"
      - "zeus.com:192.168.1.215"
      - "kdc.elasticsearch.zeus.com:192.168.1.215"
      - "kdc.schemaregistry.zeus.com:192.168.1.215"

  kdc-mf-cases:
    image: maxant/jdk
    container_name: kdc-mf-cases
    ports:
      - "8084:8084"
    environment:
      quarkus.datasource.jdbc.url: "jdbc:mysql://zeus.com:30300/mfcases"
      kafka.bootstrap.servers: "zeus.com:30001,zeus.com:30002"
      quarkus.log.handler.gelf.host: "zeus.com"
    volumes:
      - ./mf/cases/target:/project
    command:
      java -jar cases-1.0-SNAPSHOT-runner.jar -Xmx300m
    extra_hosts:
      - "contracts:127.0.0.1"
      - "pricing:127.0.0.1"
      - "web:127.0.0.1"
      - "partners:127.0.0.1"
      - "cases:127.0.0.1"
      - "waitingroom:127.0.0.1"
      - "organisation:127.0.0.1"
      - "zeus.com:192.168.1.215"
      - "kdc.elasticsearch.zeus.com:192.168.1.215"
      - "kdc.schemaregistry.zeus.com:192.168.1.215"

  kdc-mf-waitingroom:
    image: maxant/jdk
    container_name: kdc-mf-waitingroom
    ports:
      - "8085:8085"
    environment:
      kafka.bootstrap.servers: "zeus.com:30001,zeus.com:30002"
      quarkus.log.handler.gelf.host: "zeus.com"
    volumes:
      - ./mf/waitingroom/target:/project
    command:
      java -jar waitingroom-1.0-SNAPSHOT-runner.jar -Xmx300m
    extra_hosts:
      - "contracts:127.0.0.1"
      - "pricing:127.0.0.1"
      - "web:127.0.0.1"
      - "partners:127.0.0.1"
      - "cases:127.0.0.1"
      - "waitingroom:127.0.0.1"
      - "organisation:127.0.0.1"
      - "zeus.com:192.168.1.215"
      - "kdc.elasticsearch.zeus.com:192.168.1.215"
      - "kdc.schemaregistry.zeus.com:192.168.1.215"

  kdc-mf-organisation:
    image: maxant/jdk
    container_name: kdc-mf-organisation
    ports:
      - "8086:8086"
    environment:
      kafka.bootstrap.servers: "zeus.com:30001,zeus.com:30002"
      quarkus.log.handler.gelf.host: "zeus.com"
    volumes:
      - ./mf/organisation/target:/project
    command:
      java -jar organisation-1.0-SNAPSHOT-runner.jar -Xmx300m
    extra_hosts:
      - "contracts:127.0.0.1"
      - "pricing:127.0.0.1"
      - "web:127.0.0.1"
      - "partners:127.0.0.1"
      - "cases:127.0.0.1"
      - "waitingroom:127.0.0.1"
      - "organisation:127.0.0.1"
      - "zeus.com:192.168.1.215"
      - "kdc.elasticsearch.zeus.com:192.168.1.215"
      - "kdc.schemaregistry.zeus.com:192.168.1.215"
