version: '3'
services:

#  kdc-objects:
#    image: maxant/kdc-objects
#    container_name: kdc-objects
#    ports:
#      - "30601:8086"

  kdc-mf-cases:
    image: maxant/jdkrp
    container_name: kdc-mf-cases
    ports:
      - "8084:8084"
    #environment:
    #  ch.maxant.kdc.mf.library.SecurityAdapter/mp-rest/uri: "http://retropie:8086"
    volumes:
      - ./mf/cases/target:/project
    command:
      java -jar cases-1.0-SNAPSHOT-runner.jar -Xmx300m

  kdc-mf-waitingroom:
    image: maxant/jdkrp
    container_name: kdc-mf-waitingroom
    ports:
      - "8085:8085"
    volumes:
      - ./mf/waitingroom/target:/project
    command:
      java -jar waitingroom-1.0-SNAPSHOT-runner.jar -Xmx300m

  kdc-mf-organisation:
    image: maxant/jdkrp
    container_name: kdc-mf-organisation
    ports:
      - "8086:8086"
    volumes:
      - ./mf/organisation/target:/project
    command:
      java -jar organisation-1.0-SNAPSHOT-runner.jar -Xmx300m
