version: '3'
services:
  kdc-zookeeper:
    image: "maxant/zookeeper"
    container_name: "zookeeper"
    ports:
      - "30000:2181"
  kdc-kafka-1:
    image: "maxant/kafka"
    container_name: "kafka-1"
    ports:
      - "30001:9092"
    environment:
      ID: 1
      ZOOKEEPER_HOST_PORT: "zookeeper:2181"
      ADVERTISED_LISTENER_HOST_PORT: "maxant.ch:30001"
    depends_on:
      - kdc-zookeeper
  kdc-kafka-2:
    image: "maxant/kafka"
    container_name: "kafka-2"
    ports:
      - "30002:9092"
    environment:
      ID: 2
      ZOOKEEPER_HOST_PORT: "zookeeper:2181"
      ADVERTISED_LISTENER_HOST_PORT: "maxant.ch:30002"
    depends_on:
      - kdc-zookeeper
  kdc-kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: "kafdrop"
    ports:
      - "30050:9000"
    environment:
      KAFKA_BROKERCONNECT: "maxant.ch:30001,maxant.ch:30002"
    depends_on:
      - kdc-kafka-1
      - kdc-kafka-2
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - "29999:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /portainer_data:/data
#  cadvisor:
#    image: google/cadvisor:latest
#    container_name: cadvisor
#    ports:
#      - "29998:8080"
#    volumes:
#      - /var/lib/docker/:/var/lib/docker:ro
#      - /sys:/sys:ro
#      - /var/run:/var/run:rw
#      - /:/rootfs:ro
  kdc-mysql:
    image: "mysql:8.0.19"
    container_name: "kdc-mysql"
    ports:
      - "30300:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
    volumes:
      - /home/ant3/kafka-data-consistency/mysql-data:/var/lib/mysql:rw
  kdc-ksqldb-server:
    image: confluentinc/ksqldb-server:0.8.1
    hostname: ksqldb-server
    container_name: ksqldb-server
    depends_on:
      - kdc-kafka-1
      - kdc-kafka-2
    ports:
      - "30410:8088"
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: maxant.ch:30001,maxant.ch:30002
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
  kdc-ksqldb-cli:
    image: confluentinc/ksqldb-cli:0.8.1
    container_name: ksqldb-cli
    depends_on:
      - kdc-ksqldb-server
    entrypoint: /bin/sh
    tty: true

