kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: NodePort
  ports:
  - name: tcp1
    protocol: TCP
    port: 9200
    targetPort: 9200
    nodePort: 30050
  - name: tcp2
    protocol: TCP
    port: 9300
    targetPort: 9300
    nodePort: 30051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: maxant/elasticsearch
        imagePullPolicy: Never
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: discovery.type
          value: "single-node"

