kind: Service
apiVersion: v1
metadata:
  name: kafka-2
spec:
  selector:
    app: kafka-2
  ports:
  - name: tcp
    protocol: TCP
    port: 9093
    targetPort: 9093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-2
spec:
  selector:
    matchLabels:
      app: kafka-2
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-2
    spec:
      containers:
      - name: kafka-2
        image: maxant/kafka
        imagePullPolicy: Never
        ports:
        - containerPort: 9093
        env:
        - name: ID
          value: "2"
        - name: ZOOKEEPER_HOST_PORT
          value: "zookeeper.kafka-data-consistency:2181"
