# https://docs.docker.com/config/daemon/prometheus/
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first.rules"
# - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker-maxant'
      # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['dockerstats.maxant.ch']

  - job_name: 'docker-zeus'
      # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['dockerstats.zeus.com']

  - job_name: 'kdc-kafka-1'
    static_configs:
      - targets: ['kdc-kafka-1:7071']

  - job_name: 'kdc-kafka-2'
    static_configs:
      - targets: ['kdc-kafka-2:7071']

  - job_name: 'kdc-mf-contracts'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['kdc-mf-contracts:8080']

  - job_name: 'kdc-mf-pricing'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['kdc-mf-pricing:8081']

  - job_name: 'kdc-mf-web'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['kdc-mf-web:8082']

  - job_name: 'kdc-mf-partners'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['kdc-mf-partners:8083']

  - job_name: 'kdc-mf-cases'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['kdc-mf-cases:8084']

  - job_name: 'kdc-mf-waitingroom'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['kdc-mf-waitingroom:8085']

  - job_name: 'kdc-mf-organisation'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['kdc-mf-organisation:8086']

  - job_name: 'kdc-mf-billing'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['kdc-mf-billing:8087']

  - job_name: 'kdc-mf-dsc'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['kdc-mf-dsc:8088']
