kind: Service
apiVersion: v1
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  type: NodePort
  ports:
  - name: tcp
    protocol: TCP
    port: 2181
    targetPort: 2181
    nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper 
spec:
  selector:
    matchLabels:
      app: zookeeper
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: maxant/zookeeper
        imagePullPolicy: Never
        ports:
        - containerPort: 2181

